---
- name: Apache server installed
  hosts: node1
  become: yes
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
  - name: copy web.html
    copy:
      remote_src: true
      src: /home/student/rhel-workshop/ansible-files/files/web.html
      dest: /var/www/html/index.html
